# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  poker-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: poker-mysql
    volumes:
      - poker-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=poker
      - MYSQL_DATABASE=poker
      - MYSQL_USER=poker
      - MYSQL_PASSWORD=poker

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: poker-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
